#jdbc.DriverClassName=com.mysql.cj.jdbc.Driver
#  #jdbc.Url=jdbc:mysql(??:)//localhost:3306/spring_db
#jdbc.Url=jdbc:mysql://localhost:3306/spring_db
#jdbc.Username=root
#jdbc.Password=abc123
#TODO ?????????
server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: abc123
